server:
  port: 8081

spring:
  rabbitmq:
    host: rabbitmq-container
    port: 5672

keycloak:
  realm: KBE_Project_Realm
  auth-server-url: http://localhost:8080/
  ssl-required: external
  resource: API_Gateway
  public-client: true
  verify-token-audience: true
  use-resource-role-mappings: true
  confidential-port: 0